name: Scrape and Commit

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      REACT_NEWS_URL: ${{ secrets.REACT_NEWS_URL }}
      TAILWIND_NEWS_URL: ${{ secrets.TAILWIND_NEWS_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run scraper
        run: bun run scraper/index.ts

      - name: Commit changes if any
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          # Check if there are any changes
          if [ -n "$(git status --porcelain)" ]; then
            git add scraped-data.json
            git commit -m "Update: Scraped News"
            git push
          else
            echo "No changes to commit"
          fi
